// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "defaultCollection": string;
      "verifyDOI": boolean;
      "attachReason": boolean;
      "tagImported": boolean;
      "importTag": string;
      "noteTemplate": string;
    };
  }
}
